# Generated by Django 4.2.3 on 2023-08-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=100)),
                ('reg_place', models.CharField(max_length=100)),
                ('reg_address', models.CharField(max_length=100)),
                ('reg_mobno', models.IntegerField()),
            ],
        ),
    ]
