# Generated by Django 4.2.3 on 2023-09-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_prize', models.CharField(max_length=50)),
                ('pro_image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
