# Generated by Django 4.2.3 on 2023-09-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_username', models.CharField(max_length=50)),
                ('log_password', models.CharField(max_length=50)),
            ],
        ),
    ]
