# Generated by Django 4.2.3 on 2023-09-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='changepassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cha_oldpassword', models.CharField(max_length=50)),
                ('cha_newpassword', models.CharField(max_length=50)),
                ('cha_verifynewpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
